### ISSUE TITLE
Support for CronWorkflow? 

### ISSUE THREAD

**Issue by bensternlieb** [CermakM/argo-client-python#12]
Feature Request: Probably too early - but eager to use CronWorkflows!  Great library!

**Comment by CermakM** [comment]
I'll do my best to generate new models ASAP :)

**Comment by CermakM** [comment]
Hey @bensternlieb ! I just generated new models in https://github.com/CermakM/argo-client-python/pull/14 for Argo v2.5.0-rc5. Not tested yet, but if you feel adventurous, you can take them for a spin :)

**Comment by bensternlieb** [comment]
Awesome!  Will try it out.  Thanks!

**Comment by bensternlieb** [comment]
Hey @CermakM  -  Just saw that Argo released v2.5.   I checked out the branch:

```git+git://github.com/CermakM/argo-client-python.git@argo/v2.5.0#egg=argo-workflows```

but I think it might be missing some model artifacts. 

```
~/src/dl-workflow$ grep -i cron ~/.pyenv/versions/dl-workflows/lib/python3.8/site-packages/argo/workflows/client/models/__init__.py
from argo.workflows.client.models.v1alpha1_cron_workflow import V1alpha1CronWorkflow
from argo.workflows.client.models.v1alpha1_cron_workflow_list import V1alpha1CronWorkflowList
from argo.workflows.client.models.v1alpha1_cron_workflow_spec import V1alpha1CronWorkflowSpec
from argo.workflows.client.models.v1alpha1_cron_workflow_status import V1alpha1CronWorkflowStatus
~/src/dl-workflow$ ls ~/.pyenv/versions/dl-workflows/lib/python3.8/site-packages/argo/workflows/client/models/ | grep -i cron
~/src/dl-workflow$ ls ~/.pyenv/versions/dl-workflows/lib/python3.8/site-packages/argo/workflows/client/models/ | grep -i dag
v1alpha1_dag_task.py
v1alpha1_dag_template.py
```

**Comment by CermakM** [comment]
Hey @bensternlieb ... That's completely correct, I just noticed yesterday as well that I forgot to `git add` them :D I will fix that ASAP. Thanks for the heads-up!

Cheers,
M

**Comment by yxue-kabam** [comment]
exciting! going to try out the latest release (great work)

**Comment by brtasavpatel** [comment]
hi guys, just wondering was the new models generated for `v2.5.0`?

**Comment by CermakM** [comment]
Hey @brtasavpatel, the models for v2.5.0 haven't been released yet, but you can test them out already at [argo/v2.5.0](https://github.com/CermakM/argo-client-python/tree/argo/v2.5.0) branch.
